version: '3.5'

services:
  app:
    build: .
    container_name: fastapi-app
    network_mode: host
    ports:
      - "8000:8000"
    command: bash -c "uvicorn main:app --reload"
    env_file:
      - .env